steps:
  # 1) Renderizar backend/app.yaml con IP privada de Redis + conector VPC
  - name: gcr.io/cloud-builders/gcloud
    id: "Render app.yaml"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        REDIS_HOST=$(gcloud redis instances describe ${_REDIS_INSTANCE} --region ${_REGION} --format='value(host)')
        sed -e "s/REDIS_HOST_PLACEHOLDER/${REDIS_HOST}/g" \
            -e "s#VPC_CONNECTOR_FULL_PLACEHOLDER#${_VPC_CONNECTOR}#g" \
            app.template.yaml > backend/app.yaml
        echo "===== backend/app.yaml ====="
        cat backend/app.yaml

  - name: gcr.io/cloud-builders/npm
    dir: "backend"
    args: ["ci"]
  - name: gcr.io/cloud-builders/npm
    dir: "backend"
    args: ["run","build"]

  - name: gcr.io/cloud-builders/gcloud
    id: "Deploy App Engine"
    args: ["app","deploy","backend/app.yaml","--quiet"]

substitutions:
  _REGION: "europe-west1"
  _REDIS_INSTANCE: "app-redis"
  _VPC_CONNECTOR: "projects/maquicontrol-90a19/locations/europe-west1/connectors/app-connector"

options:
  logging: CLOUD_LOGGING_ONLY
