runtime: nodejs20
service: poketest

handlers:
  - url: /.*
    script: auto

env_variables:
  POKEAPI_BASE: "https://pokeapi.co/api/v2"
  CACHE_TTL_SECONDS: "300"
  REDIS_URL: "redis://default:bVBwKU6ocaOoQJfLjmYuFHbpSECSHFaw@redis-10413.c304.europe-west1-2.gce.redns.redis-cloud.com:10413"


